// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxnikregrasjkjntoyhm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bmlrcmVncmFzamtqbnRveWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjE1MDUsImV4cCI6MjA3MTQ5NzUwNX0.pW5rprMNMSVagEqBbLic-4pz0B6qWkA4qz7BY2-YvuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});